### ISSUE TITLE
how to config IMapper inject Singleton

### ISSUE THREAD

**Issue by djl394922860** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#51] opened 2018-04-25 06:09 UTC
I see the source code below：
`return services.AddScoped<IMapper>(sp => new Mapper(sp.GetRequiredService<IConfigurationProvider>(), sp.GetService));`
but i want to use singleton ?

**Comment by lbargaoanu** [comment] 2018-04-25 06:31
Duplicate of #41.

**Closed by lbargaoanu** 2018-04-25 06:31 UTC

**Comment by djl394922860** [comment] 2018-04-25 13:24
got it , thank you for your reply !
